### ISSUE TITLE
ModCore relicensing

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/ModCore#149]
This issue serves as a means for users I can't contact via Discord or other means to give permission for the relicense to AGPL.

Do you guys consent to ModCore being relicensed from MIT to AGPL?

@DrCreo @Drake103 @aexolate

**Comment by Naamloos** [comment]
Also: I'm taking screenshots for a gist with the permissions.

**Comment by DrCreo** [comment]
I consent,

**Comment by Naamloos** [comment]
Update: none of the code committed by @Drake103 remains in the commit tree as of the feature/interactions branch (which will end up being merge into master, with the new license.)

Yet still it would be favorable to still get permission, to prevent complications.

**Comment by aexolate** [comment]
I consent

**Comment by Drake103** [comment]
I consent (though a bit late).
