### ISSUE TITLE
ideabot

### ISSUE THREAD

**Issue by uwx** [Naamloos/ModCore#69]
- [x] poll support
- [x] set up to give role on reaction
- [x] set up to give role on join
- [ ] #113
- [x] avatar change log (and possibly other types of changes)
- [x] nickname change request system
- [ ] #114
- [ ] #115
- [x] Slowmode
- [ ] #116
- [x] Todo lists
- [x] Additional strawpoll creator next to the reaction poll system
- [ ] #117
- [x] Snipe command
- [ ] #118
- [ ] #119
- [ ] #120
- [ ] #121
- [ ] #122
- [ ] Mass mention filter (with exempt of course)
- [ ] #123
- [ ] Feedback system (DM Naamloos(?))
- [ ] Temporary channel locks
- [ ] Starboard leaderboards
- [ ] #124
- [ ] #125
- [ ] #127
- [ ] #126

**Comment by uwx** [comment]
HOW DO YOU DO CHECKBOXES IN MARKDOWN

**Comment by NaamloosDT** [comment]
lemme edit it for ya

**Comment by uwx** [comment]
THANKS NAAAAAM

**Comment by NaamloosDT** [comment]
there ya go

**Comment by NaamloosDT** [comment]
polling should be easy, that's like 10 lines with interactivity

**Comment by NaamloosDT** [comment]
Ticked poll support. Issues with polling are lib-side.

**Comment by NaamloosDT** [comment]
I guess joinroles can be added via Guild Config. Saves me some trouble with setting up DB.

**Comment by NaamloosDT** [comment]
Role on join was already implemented.
Check 90bd06839aad6a5de2ba9168938235786850267c and 71b2b49b177bb8bf1cd89f93317898883d7a5a11

**Comment by NaamloosDT** [comment]
ticked join roles.

**Comment by NaamloosDT** [comment]
Added:
`Integration for https://discordbots.org/`
`Integration for https://bots.discord.pw`

**Comment by NaamloosDT** [comment]
ticked away `set up to give role on reaction`

**Comment by NaamloosDT** [comment]
added three new goals

**Comment by NaamloosDT** [comment]
Added a bunch of new ideas to keep me busy

**Comment by NaamloosDT** [comment]
Removed `Integration for https://bans.discordlist.net/` because that site seems to not exist anymore

**Comment by NaamloosDT** [comment]
haha wait this is issue 69

what could've gone wrong :^)

**Comment by NaamloosDT** [comment]
checked item `todo lists`

**Comment by NaamloosDT** [comment]
ticking off avatar change log, pushing it rn.
Adding "snipe command"

**Comment by NaamloosDT** [comment]
Ticked off slowmode as Discord has that as a built in feature. Might consider adding custom slowmode (Discord's UI allows for specific values, the API accepts pretty much any integer value)

**Comment by NaamloosDT** [comment]
0-21600 seconds

**Comment by NaamloosDT** [comment]
Snipe command is added

**Comment by Naamloos** [comment]
Claiming verification system

**Comment by Naamloos** [comment]
Closing this issue as I created separate issues for features I still want.
