### ISSUE TITLE
[IDEA] Custom commands

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/ModCore#76]
I want to add something to allow users to build their own commands. When in beta I want to allow people to build their own JSON that gets validated and parsed to a command. Later on I want to build a graphical command builder which might be similar to scratch, I'm not sure yet.

Example ModCoreCommand format:
```json
{
    "parameters":[
        {"name" : "user", "type" : "member"},
        {"name" : "nickname", "type" : "string"},
    ],
    "actions":[
        {"action" : "setnickname", "parameters" : [ "param:user", "param:nickname" ] }
    ]
}
```

I'll still have to think of notations for stuff like if-statements, but I think this might work out fine.

Commands will be:
`$[command name] args` for calling custom commands
`$customcommands` for listing custom commands

**Comment by NaamloosDT** [comment]
parameters will be the command parameters

**Comment by Craftplacer** [comment]
Why not let users write their own JS files? *cough* DBC *cough* ;)

**Comment by NaamloosDT** [comment]
I'll have to have some degree of control over what users can do. I don't want to give _too_ much freedom. Having users just write js code will allow them to e.g. write endless loops which might clog up my memory. This action system will be fairly primitive, but anyone wanting to write something more complex will most likely be competent enough to write their own bots anyway.

**Comment by Craftplacer** [comment]
Do you think it will be end user friendly to use? Also depends how far you want to make it customizable.

**Comment by NaamloosDT** [comment]
the graphical code editor might eventually be a good way to teach people some basics of computer programming

**Comment by Naamloos** [comment]
Considering dropping this issue / idea because I simply do not have the time to implement this all.

**Comment by Naamloos** [comment]
Dropping idea for now.
