### ISSUE TITLE
Buildmessage with an empty embed sends... an embed.

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/ModCore#79]
Might want to fix that

![](https://i.imgur.com/tWplFNl.png)

**Comment by Emzi0767** [comment]
This behaviour is actually intentional, and it's from the underlying library (D#+). Instead of building an empty embed, it should be nulled.

**Comment by Naamloos** [comment]
@Emzi0767 yes, that's why i made the issue on _modcore_ and not on the underlying lib
