### ISSUE TITLE
Update to .Net Core 3.0

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/ModCore#80]
it's here boys

might do it myself, if you're lucky you might be faster

**Comment by kylesalk** [comment]
I can give this one a go. The PR might take until the first weekend in Oct., so feel free to close out the issue if you end up working on it before then!

**Comment by Naamloos** [comment]
@kylesalk alrighty, thanks in advance! It'll probably take me just as long to update to vs2019 😝

**Comment by Naamloos** [comment]
The PR above has been marked invalid until further notice from the author. I feel like just updating the framework isn't enough.
